### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tanner-ducharme** [huridocs/python_uwazi_API#1]
when I try to install the repo with:
`python3 -m pip install git+https://github.com/huridocs/python_uwazi_API.git`

I get the following error:
`ERROR: git+https://github.com/huridocs/python_uwazi_API.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

Trying another method, when I try first cloning the repo:
`git clone https://github.com/huridocs/python_uwazi_API.git`

installing the requirements:
`cd python_uwazi_API/ && pip3 install -r ./requirements.txt`

 and installing the library:
`pip3 install -e .`

I get a similar error:
`ERROR: file:///Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/python_uwazi_API does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

If someone could please advise on how to proceed it would be greatly appreciated. Thanks!

**Comment by thebutcher00** [comment]
hi @txau , Thank you so much for sharing the documentation, Since I have installed zyte and we already have Uwazi installed, Right now i dont seems to able to connect to the Uwazi, I did followed those steps, git clone git@github.com:huridocs/python_uwazi_API.git
cd python_uwazi_API
source ../py3/bin/activate       # since I use virtual envs, this may be the difference
pip install --upgrade pip          # upgrade was needed as well to make it work
pip install -r requirements.txt
it would be great help if you can point out how can I establish connection,  
Thank you .

**Comment by txau** [comment]
cc  @gabriel-piles

**Comment by gabriel-piles** [comment]
@thebutcher00 

To establish a connection, you can use the following Python commands, replacing the placeholder values for user, password, and URL with the correct information:


from uwazi_adapter.UwaziAdapter import UwaziAdapter

uwazi_adapter = UwaziAdapter(user='admin', password='admin', url='http://localhost:3000')


# Then, you can create a new entity with the following commands

entity = dict()
entity["template"] = put template id here
entity["title"] = put title here
entity["type"] = "entity"
entity["language"] = "en"
entity["metadata"] = dict()
entity["metadata"][put metadata select id here] = [{"value": put thesauri id here}]
entity["metadata"][put metadata text id here] = [{"value": put text here}]

uwazi_adapter.entities.upload(entity=entity, language="en")


Explore the full range of endpoints in the README file: README.md: https://github.com/huridocs/uwazi

If you encounter any challenges, please provide detailed information about the specific errors or issues you're facing. This will enable me to offer more tailored assistance.

Thank you.

**Comment by thebutcher00** [comment]
Hi @gabriel-piles, 
Thank you for the prompt response. Will try to add more details along with the issue I am facing. Thanks in advance.

**Comment by thebutcher00** [comment]
Hi @gabriel-piles, create template and 

> @thebutcher00
> 
> To establish a connection, you can use the following Python commands, replacing the placeholder values for user, password, and URL with the correct information:
> 
> from uwazi_adapter.UwaziAdapter import UwaziAdapter
> 
> uwazi_adapter = UwaziAdapter(user='admin', password='admin', url='http://localhost:3000')
> 
> Then, you can create a new entity with the following commands
> 
> entity = dict() entity["template"] = put template id here entity["title"] = put title here entity["type"] = "entity" entity["language"] = "en" entity["metadata"] = dict() entity["metadata"][put metadata select id here] = [{"value": put thesauri id here}] entity["metadata"][put metadata text id here] = [{"value": put text here}]
> 
> uwazi_adapter.entities.upload(entity=entity, language="en")
> 
> Explore the full range of endpoints in the README file: README.md: https://github.com/huridocs/uwazi
> 
> If you encounter any challenges, please provide detailed information about the specific errors or issues you're facing. This will enable me to offer more tailored assistance.
> 
> Thank you.
Hi @gabriel-piles 
I have configured the upload_entity python file with uwazi credential and entity data, However I am unable to push content. It would be great help if you can guide me how to push the content into Uwazi template. 
Thank you.
