### ISSUE TITLE
posting a template entity

### ISSUE THREAD

**Issue by tanner-ducharme** [huridocs/python_uwazi_API#2]
I've managed to establish a connection to our server, but I cannot figure out how to post an entity. 

I want to post a basic entity to a template called 'test'

The template consists of a title string, a text-body string, and a date. How do I achieve this?

Thanks

@natasha-todi
@pddocs

**Comment by txau** [comment]
@tanner-ducharme take a look to https://github.com/huridocs/python_uwazi_API/blob/af910b24436903b8a16ff5a17784bf4a5458be45/uwazi_api/Entities.py#L77

I don't have a code example in python at the moment, maybe @gabriel-piles can provide one. Start with the simplest possible thing sending the smallest possible entity which must contain the properties:
- Title
- Template id

From there try to add more properties nested in the metadata property. You can inspect your network connection in your browser and create an entity via the UI, that way you can have an idea on the structure and params of the object.

**Comment by tanner-ducharme** [comment]
I tried to create an `UwaziRequest` object (as it's an arg for `Entities`):

`u_request = UwaziRequest(user='myuser', password='mypassword', url='https://ral.uwazi.io/en/')`

and I got the following error:
`Traceback (most recent call last):
  File "test_post.py", line 26, in <module>`<br>`
    uwazi_request = UwaziRequest(user=user, password=password, url=url)`<br>`
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/uwazi_api/UwaziRequest.py", line 16, in __init__
    self.connect_sid = self.get_connect_sid()`<br>`
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/uwazi_api/UwaziRequest.py", line 24, in get_connect_sid`<br>`
    return response.cookies['connect.sid']`<br>`
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/env/lib/python3.7/site-packages/requests/cookies.py", line 328, in __getitem__`<br>`
    return self._find_no_duplicates(name)`<br>`
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/env/lib/python3.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates`<br>`
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='connect.sid', domain=None, path=None"`

The same authentication worked `UwaziAdapter`, so shouldn't it work here as well?

Thanks

**Comment by gabriel-piles** [comment]
hello @tanner-ducharme 

For uploading an entity you can use the following piece of code:

```
uwazi_adapter = UwaziAdapter(user='admin', password='admin', url='http://localhost:3000')
entity = {'title': 'title_of_the_entity',
           'template': 'template_id_like_4e57cdd6f54e0a1304c0d5dd',
           'metadata': {'property_name': [{'value': "property_value"}], 'other_property_name':[{'value': "property_value"}]}}

shared_id = uwazi_adapter.entities.upload(entity=entity, language='en')
print(uwazi_adapter.entities.get_one(shared_id=shared_id, language='en'))
```

You should know the template id and the properties names. 

The template you can know it from the URL when you are editing a template:

http://localhost:3000/settings/templates/edit/<b>4d8cdec361cde0408222d3dd</b>


The properties names are the names of the properties in lowercase and replacing spaces and special characters to underscores:

`Regional Group -> regional_group`

The date value, you should use a timestamp:

```
from datetime import datetime

date_timestamp_int = int(datetime.now().timestamp())

# 'metadata': {'date_name': [{'value': date_timestamp_int}]}}
```

Let me know if you achieved to upload a entity.

Best

**Comment by tanner-ducharme** [comment]
just as I was before, when creating an `UwaziApadpter` object with:
`uwazi_adapter = UwaziAdapter(user=myuser, password=mypassword, url=myurl)`

I get the same error as before

`Traceback (most recent call last):
  File "test_post.py", line 29, in <module>
    uwazi_adapter = UwaziAdapter(user=user, password=password, url=url)
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/uwazi_api/UwaziAdapter.py", line 14, in __init__
    self.uwazi_request = UwaziRequest(url, user, password)
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/uwazi_api/UwaziRequest.py", line 16, in __init__
    self.connect_sid = self.get_connect_sid()
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/uwazi_api/UwaziRequest.py", line 24, in get_connect_sid
    return response.cookies['connect.sid']
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/env/lib/python3.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi_project/env/lib/python3.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='connect.sid', domain=None, path=None"`


I thought it might be an issue with the `requests` library, so I checked and my environment is inline with the requirements.txt

How should I proceed? Thanks

**Comment by gabriel-piles** [comment]
Hello @tanner-ducharme 

To use the Uwazi Request you should use the URL without the language neither the last backslash as following:

u_request = UwaziRequest(user='myuser', password='mypassword', url='<b>https://ral.uwazi.io</b>')

However, I would recommend to use the UwaziAdapter class.

I updated the repository with a URL sanitizer method to be able to use the URL in the UwaziAdapter with the backslash and the language.

Best

**Comment by tanner-ducharme** [comment]
@gabriel-piles I was able to upload an entity, thanks for your help!
