### ISSUE TITLE
error upload: maximum field length

### ISSUE THREAD

**Issue by tanner-ducharme** [huridocs/python_uwazi_API#4]
When trying to upload an article, I get the following error:

```
Error uploading entity 422 
{"error":"validation failed",
"validations":
[{"keyword":"metadataMatchesTemplateProperties",
"schemaPath":"#/metadataMatchesTemplateProperties",
"params":{"keyword":"metadataMatchesTemplateProperties"},
"dataPath":".metadata['article_contents']",
"message":"maximum field length exceeded"}],
"prettyMessage":"validation failed",
"requestId":8694} 

{'title': 'Farewell Letters: A Tribute to the Civil Society Groups, Bloggers, and Media Outlets We Lost in 2021', 
'template': '5d7fa0edabfb862c766385b3', 
'metadata': {...}
```

It appears that the article text is too long. I have two questions related to this issue:

1. Is there any way around this?
2. What is the maximum field length for Uwazi?

Thanks

@natasha-todi
@pddocs

**Comment by txau** [comment]
@tanner-ducharme there is indeed an on-going issue related to this: https://github.com/huridocs/uwazi/issues/4520 . Hopefully we can release a patch soon.

1. Currently there is no way around this but I'll try to prioritize this issue.
2. For texts there should be no limit (or very big, in the range of thousands of pages) but we have a problem in our elastic mappings that is triggering this bug.

**Comment by tanner-ducharme** [comment]
okay, it seems like when doing a mass upload that this doesn't prevent the other articles from being uploaded, so it's not a critical problem for the time being. Thanks
